import os
import sys
import glob
import requests
import json
import re
from datetime import datetime
import urllib3
import time

# Disable SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def get_latest_draft():
    drafts = glob.glob("_drafts/*.md")
    if not drafts:
        return None
    return max(drafts, key=os.path.getctime)

def parse_research_data():
    path = "context/research-queue.json"
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except:
            return []

def call_gemini_with_retry(url, payload, max_retries=3):
    for i in range(max_retries):
        res = requests.post(url, json=payload, timeout=60)
        if res.status_code == 200:
            return res
        elif res.status_code == 429:
            print(f"Quota exceeded. Retrying in 60s... (Attempt {i+1}/{max_retries})")
            time.sleep(60)
        else:
            print(f"API Error: {res.status_code} - {res.text}")
            break
    return None

def main():
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_key:
        print("Missing GEMINI_API_KEY")
        sys.exit(1)

    target_file = get_latest_draft()
    if not target_file:
        print("No drafts found.")
        sys.exit(0)

    print(f"Generating technical visuals for: {target_file}")
    
    with open(target_file, "r", encoding="utf-8") as f:
        content = f.read()

    research_data = parse_research_data()
    if not research_data:
        print("No research data found to visualize.")
        sys.exit(0)

    top_research = research_data[0]
    metrics = top_research.get("summary", "")
    
    # Construction of SVG Prompt
    prompt = f"""
    Based on the following data, generate a clean, modern SVG code for a technical diagram.
    
    DATA: {metrics}
    
    AESTHETIC: 'Organic Precision'.
    COLORS: Primary #0F1A15, Secondary #C5B388, Accent #2C3330.
    REQUIREMENTS:
    - Return ONLY the raw <svg>...</svg> code.
    - No markdown formatting, no explanation.
    - Include text labels for key data points.
    - Use a width of 800 and dynamic height.
    """

    url = f"https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key={gemini_key}"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2}
    }

    print("Calling Gemini 1.5 Flash for SVG generation...")
    res = call_gemini_with_retry(url, payload)
    
    if not res:
        print("Failed to get SVG from Gemini.")
        sys.exit(1)
        
    res_json = res.json()
    try:
        svg_text = res_json['candidates'][0]['content']['parts'][0]['text']
        # Clean up if AI added markdown code blocks
        svg_text = re.sub(r'```svg\n?', '', svg_text)
        svg_text = re.sub(r'```\n?', '', svg_text).strip()
        
        if not svg_text.startswith("<svg"):
            print("Invalid SVG output.")
            sys.exit(1)

        # 4. Save SVG
        slug = os.path.basename(target_file).replace('.md', '')
        year = datetime.now().strftime("%Y")
        img_dir = f"assets/images/{year}/{slug}"
        os.makedirs(img_dir, exist_ok=True)
        img_filename = "technical_diagram_1.svg"
        img_path = f"{img_dir}/{img_filename}"
        
        with open(img_path, "w", encoding="utf-8") as f:
            f.write(svg_text)
            
        print(f"Saved SVG diagram to: {img_path}")

        # 5. Update Markdown
        markdown_ref = f"\n\n![Technical Diagram: {top_research['title']}](/images/{year}/{slug}/{img_filename})\n*Figure 1: Technical visualization generated by image-agent.*\n"
        
        if "##" in content:
            parts = content.split("##", 2)
            if len(parts) > 2:
                new_content = parts[0] + "##" + parts[1] + markdown_ref + "##" + parts[2]
            else:
                new_content = content + markdown_ref
        else:
            new_content = content + markdown_ref

        with open(target_file, "w", encoding="utf-8") as f:
            f.write(new_content)
            
        print("Successfully integrated technical SVG into post.")

    except Exception as e:
        print(f"Processing failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
